name: 6-Hour Sync Search

on:
  schedule:
    - cron: '0 */6 * * *' # يشتغل كل 6 ساعات بالتمام
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  run-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ضروري جداً ليقدر يحفظ الكاش
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas requests

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Commit and Push Progress
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images_cache.json Across_MENA_Final_Report.csv
          git commit -m "حفظ التقدم التلقائي - كملنا جزء من الصور" || echo "لا توجد تغييرات للحفظ"
          git push
