name: Extract and Push to Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ضروري عشان يقدر يضيف ملفات للريبو
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pdfplumber pandas openpyxl arabic-reshaper python-bidi

      - name: Run Script
        run: python process_customs.py

      - name: Commit and Push file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add test_output_50.xlsx
          git commit -m "Add extracted excel file"
          git push
