name: Extract and Push to Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # استخدام التوكن الافتراضي

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pdfplumber pandas openpyxl arabic-reshaper python-bidi

      - name: Run Script
        run: python process_customs.py

      - name: Check if file exists
        run: ls -l test_output_50.xlsx # للتأكد أن الملف انخلق فعلياً

      - name: Commit and Push file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add test_output_50.xlsx
          git commit -m "Add test output file" || echo "No changes to commit"
          git push origin main # تأكد أن اسم الفرع عندك main (إذا كان master غيره لـ master)
